package com.vcampus.common.model;

public enum NotificationType {
    SCHEDULE_ASSIGNED,
    GRADE_PUBLISHED,
    STUDENT_STATUS_CHANGED,
    ROLES_CHANGED,
    ACCOUNT_ENABLED,
    ACCOUNT_DISABLED,
    PASSWORD_RESET,
    LIBRARY_BORROWED,
    LIBRARY_RENEWED,
    LIBRARY_RETURNED,
    LIBRARY_LOST,
    LIBRARY_DUE_SOON,
    LIBRARY_OVERDUE,
    FORUM_POST_COMMENTED,
    FORUM_POST_MODERATED,
    FORUM_COMMENT_MODERATED,
    BANK_TRANSFER_RECEIVED,
    BANK_ACCOUNT_TOPPED_UP,
    BANK_ACCOUNT_STATUS_CHANGED,
    SHOP_ORDER_SHIPPED
}
