package com.vcampus.client.ui;

import com.vcampus.client.network.VCampusClient;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.time.*;
import java.util.*;
import java.util.List;

final class LibraryCatalogPanel extends LibraryPanel {
    private final JTextField keyword=field(18),category=field(10);private final DefaultTableModel model=new DefaultTableModel(new Object[]{"书名","作者","分类","ISBN","可借/总藏"},0){public boolean isCellEditable(int r,int c){return false;}};private final JTable table=new JTable(model);private final JLabel pageLabel=new JLabel("第 1 页");private java.util.List<LibraryViewData.CatalogRow>rows=List.of();private int page=1,total;
    LibraryCatalogPanel(VCampusClient c,String t){super(c,t);setLayout(new BorderLayout(0,14));JPanel bar=toolbar();bar.add(new JLabel("关键词"));bar.add(keyword);bar.add(new JLabel("分类"));bar.add(category);JButton search=primary("检索馆藏");bar.add(search);add(bar,BorderLayout.NORTH);styleTable(table);add(scroll(table),BorderLayout.CENTER);JPanel foot=new JPanel(new BorderLayout());foot.setOpaque(false);JPanel paging=new JPanel(new FlowLayout(FlowLayout.LEFT));paging.setOpaque(false);JButton prev=quiet("上一页"),next=quiet("下一页"),detail=quiet("查看详情"),borrow=mutation("借阅选中图书");paging.add(prev);paging.add(pageLabel);paging.add(next);JPanel actions=new JPanel(new FlowLayout(FlowLayout.RIGHT));actions.setOpaque(false);actions.add(detail);actions.add(borrow);foot.add(paging,BorderLayout.WEST);foot.add(actions,BorderLayout.EAST);add(foot,BorderLayout.SOUTH);search.addActionListener(e->{page=1;refresh();});prev.addActionListener(e->{if(page>1){page--;refresh();}});next.addActionListener(e->{if(page*10<total){page++;refresh();}});detail.addActionListener(e->detail());borrow.addActionListener(e->borrow());refresh();}
    void refresh(){String keywordValue=keyword.getText().trim();String categoryValue=category.getText().trim();int pageNumber=page;runRequest(()->client.searchLibraryCatalog(sessionToken,keywordValue,categoryValue,pageNumber),r->{var p=LibraryViewData.catalogPage(r);rows=p.rows();total=p.total();model.setRowCount(0);for(var x:rows)model.addRow(new Object[]{x.title(),x.authors(),x.category(),x.isbn().isBlank()?"—":x.isbn(),x.availableCopies()+" / "+x.totalCopies()});pageLabel.setText("第 "+p.page()+" 页 · 共 "+p.total()+" 项");});}
    private void detail(){int i=selected(table);if(i<0)return;var x=rows.get(i);JTextArea text=new JTextArea("《"+x.title()+"》\n\n书目编号："+x.catalogCode()+"\n作者："+x.authors()+"\n出版社："+x.publisher()+"\n出版年："+(x.publishYear()==null?"—":x.publishYear())+"\n分类："+x.category()+"\nISBN："+(x.isbn().isBlank()?"—":x.isbn())+"\n馆藏："+x.availableCopies()+" 可借 / "+x.totalCopies()+" 总计\n\n"+x.description());text.setEditable(false);text.setLineWrap(true);text.setWrapStyleWord(true);text.setRows(12);text.setColumns(42);text.setBorder(BorderFactory.createEmptyBorder(10,10,10,10));JOptionPane.showMessageDialog(this,new JScrollPane(text),"图书详情",JOptionPane.INFORMATION_MESSAGE);}
    private void borrow(){int i=selected(table);if(i<0)return;var x=rows.get(i);if(!x.enabled()){error("该书目已停用，暂不可借阅");return;}if(x.availableCopies()<1){error("当前没有可借馆藏");return;}runRequest(()->client.myLibraryLoans(sessionToken,"all",1),rulesResponse->{var rules=LibraryViewData.loanPage(rulesResponse);int days=rules.initialLoanDays()==null?0:rules.initialLoanDays();Instant estimate=Instant.now().plus(Duration.ofDays(days));int choice=JOptionPane.showConfirmDialog(this,"借阅《"+x.title()+"》？\n借期："+days+" 天\n预计到期："+estimate.toString().substring(0,10)+"\n最终日期以服务器回执为准。","确认借阅",JOptionPane.YES_NO_OPTION);if(choice==JOptionPane.YES_OPTION)runRequest(()->client.borrowLibraryBook(sessionToken,x.bookId()),receipt->{var m=LibraryViewData.receipt(receipt);info("借阅成功，到期时间："+m.dueAt());refresh();});});}
}
