package com.vcampus.client.ui;

import com.vcampus.common.model.*;
import com.vcampus.common.protocol.ResponseMessage;
import com.vcampus.common.protocol.RowCodec;
import java.time.Instant;
import java.util.*;

public final class LibraryViewData {
    private static final String ERROR="服务器返回的图书馆数据格式不正确";
    private LibraryViewData() {}

    public static CatalogPage catalogPage(ResponseMessage response){try{Map<String,String>d=data(response);int count=nonNegative(d,"count");List<CatalogRow>rows=new ArrayList<>();for(int i=0;i<count;i++){List<String>f=row(d,i,12);rows.add(new CatalogRow(l(f,0),f.get(1),blank(f.get(2)),f.get(3),f.get(4),f.get(5),nullableInt(f.get(6)),f.get(7),f.get(8),bool(f.get(9)),integer(f,10),integer(f,11)));}return new CatalogPage(rows,positive(d,"page"),positive(d,"pageSize"),nonNegative(d,"total"));}catch(Exception e){throw malformed(e);}}
    public static LoanPage loanPage(ResponseMessage response){try{Map<String,String>d=data(response);int count=nonNegative(d,"count");List<LoanRow>rows=new ArrayList<>();for(int i=0;i<count;i++){List<String>f=row(d,i,16);rows.add(new LoanRow(l(f,0),l(f,1),f.get(2),f.get(3),l(f,4),f.get(5),f.get(6),f.get(7),Instant.parse(f.get(8)),Instant.parse(f.get(9)),integer(f,10),instant(f.get(11)),en(f.get(12),LibraryReturnCondition.class),LibraryLoanChannel.valueOf(f.get(13)),bool(f.get(14)),bool(f.get(15))));}return new LoanPage(rows,positive(d,"page"),positive(d,"pageSize"),nonNegative(d,"total"),optionalInt(d,"maxLoans"),optionalInt(d,"initialLoanDays"),optionalInt(d,"renewalDays"));}catch(Exception e){throw malformed(e);}}
    public static CopyPage copyPage(ResponseMessage response){try{Map<String,String>d=data(response);int count=nonNegative(d,"count");List<CopyRow>rows=new ArrayList<>();for(int i=0;i<count;i++){List<String>f=row(d,i,8);rows.add(new CopyRow(l(f,0),l(f,1),f.get(2),f.get(3),f.get(4),LibraryCopyStatus.valueOf(f.get(5)),blank(f.get(6)),Instant.parse(f.get(7))));}return new CopyPage(rows,positive(d,"page"),positive(d,"pageSize"),nonNegative(d,"total"));}catch(Exception e){throw malformed(e);}}
    public static BorrowerPreview borrowerPreview(ResponseMessage response){try{Map<String,String>d=data(response);return new BorrowerPreview(l(d,"borrowerUserId"),required(d,"username"),required(d,"displayName"),UserRole.valueOf(required(d,"baseIdentity")),l(d,"copyId"),l(d,"bookId"),required(d,"title"),required(d,"barcode"),LibraryCopyStatus.valueOf(required(d,"copyStatus")),nullableLong(d.get("activeLoanId")),integer(d,"activeLoans"),integer(d,"maxLoans"),bool(required(d,"overdue")),bool(required(d,"allowed")),required(d,"message"));}catch(Exception e){throw malformed(e);}}
    public static MutationReceipt receipt(ResponseMessage response){try{Map<String,String>d=data(response);return new MutationReceipt(nullableLong(d.get("loanId")),nullableLong(d.get("copyId")),blank(d.get("barcode")),blank(d.get("title")),instant(d.get("dueAt")),instant(d.get("returnedAt")),blank(d.get("condition")),response.message());}catch(Exception e){throw malformed(e);}}

    private static Map<String,String>data(ResponseMessage r){if(r==null||!r.success())throw new IllegalArgumentException();return r.data();}private static List<String>row(Map<String,String>d,int i,int size){List<String>f=RowCodec.decode(required(d,"row."+i));if(f.size()!=size)throw new IllegalArgumentException();return f;}private static String required(Map<String,String>d,String k){String v=d.get(k);if(v==null)throw new IllegalArgumentException();return v;}private static int integer(Map<String,String>d,String k){return Integer.parseInt(required(d,k));}private static int nonNegative(Map<String,String>d,String k){int v=integer(d,k);if(v<0)throw new IllegalArgumentException();return v;}private static int positive(Map<String,String>d,String k){int v=integer(d,k);if(v<1)throw new IllegalArgumentException();return v;}private static long l(Map<String,String>d,String k){return Long.parseLong(required(d,k));}private static long l(List<String>f,int i){return Long.parseLong(f.get(i));}private static int integer(List<String>f,int i){return Integer.parseInt(f.get(i));}private static Integer nullableInt(String v){return v==null||v.isBlank()?null:Integer.valueOf(v);}private static Integer optionalInt(Map<String,String>d,String k){return nullableInt(d.get(k));}private static Long nullableLong(String v){return v==null||v.isBlank()?null:Long.valueOf(v);}private static Instant instant(String v){return v==null||v.isBlank()?null:Instant.parse(v);}private static String blank(String v){return v==null?"":v;}private static boolean bool(String v){if("true".equalsIgnoreCase(v))return true;if("false".equalsIgnoreCase(v))return false;throw new IllegalArgumentException();}private static <E extends Enum<E>>E en(String v,Class<E>c){return v==null||v.isBlank()?null:Enum.valueOf(c,v);}private static IllegalArgumentException malformed(Exception e){return new IllegalArgumentException(ERROR,e);}

    public record CatalogRow(long bookId,String catalogCode,String isbn,String title,String authors,String publisher,Integer publishYear,String category,String description,boolean enabled,int totalCopies,int availableCopies){}
    public record CatalogPage(List<CatalogRow>rows,int page,int pageSize,int total){public CatalogPage{rows=List.copyOf(rows);}}
    public record LoanRow(long loanId,long bookId,String isbn,String title,long copyId,String barcode,String borrowerUsername,String borrowerDisplayName,Instant borrowedAt,Instant dueAt,int renewalCount,Instant returnedAt,LibraryReturnCondition returnCondition,LibraryLoanChannel channel,boolean overdue,boolean renewable){}
    public record LoanPage(List<LoanRow>rows,int page,int pageSize,int total,Integer maxLoans,Integer initialLoanDays,Integer renewalDays){public LoanPage{rows=List.copyOf(rows);}}
    public record CopyRow(long copyId,long bookId,String barcode,String title,String shelfLocation,LibraryCopyStatus status,String statusReason,Instant updatedAt){}
    public record CopyPage(List<CopyRow>rows,int page,int pageSize,int total){public CopyPage{rows=List.copyOf(rows);}}
    public record BorrowerPreview(long borrowerUserId,String username,String displayName,UserRole baseIdentity,long copyId,long bookId,String title,String barcode,LibraryCopyStatus copyStatus,Long activeLoanId,int activeLoans,int maxLoans,boolean overdue,boolean allowed,String message){}
    public record MutationReceipt(Long loanId,Long copyId,String barcode,String title,Instant dueAt,Instant returnedAt,String condition,String message){}
}
