package com.vcampus.client.ui;

import com.vcampus.client.network.VCampusClient;
import com.vcampus.common.model.*;
import javax.swing.*;
import java.awt.*;

final class LibraryCirculationPanel extends LibraryPanel {
    private final JTextField username=field(14),barcode=field(14),reason=field(20);private final JComboBox<LibraryCirculationOperation>operation=new JComboBox<>(LibraryCirculationOperation.values());private final JComboBox<LibraryReturnCondition>condition=new JComboBox<>(LibraryReturnCondition.values());private final JTextArea preview=new JTextArea();private final JButton execute=mutation("办理");private LibraryViewData.BorrowerPreview current;
    LibraryCirculationPanel(VCampusClient c,String t){super(c,t);setLayout(new BorderLayout(0,16));JPanel bar=toolbar();bar.add(new JLabel("用户名"));bar.add(username);bar.add(new JLabel("馆藏条码"));bar.add(barcode);bar.add(new JLabel("业务"));bar.add(operation);JButton check=primary("校验信息");bar.add(check);add(bar,BorderLayout.NORTH);preview.setEditable(false);preview.setFont(preview.getFont().deriveFont(16f));preview.setBorder(BorderFactory.createEmptyBorder(24,28,24,28));preview.setBackground(Theme.SURFACE_HOVER);add(new JScrollPane(preview),BorderLayout.CENTER);JPanel action=new JPanel(new FlowLayout(FlowLayout.RIGHT,10,8));action.setOpaque(false);action.add(new JLabel("归还状态"));action.add(condition);action.add(new JLabel("原因"));action.add(reason);execute.setEnabled(false);action.add(execute);add(action,BorderLayout.SOUTH);check.addActionListener(e->validateInput());execute.addActionListener(e->execute());operation.addActionListener(e->{current=null;execute.setEnabled(false);});}
    private void validateInput(){runRequest(()->client.previewLibraryCirculation(sessionToken,username.getText().trim(),barcode.getText().trim(),(LibraryCirculationOperation)operation.getSelectedItem()),r->{current=LibraryViewData.borrowerPreview(r);preview.setText("借阅人："+current.displayName()+"（"+current.username()+"）\n基础身份："+current.baseIdentity()+"\n当前借阅："+current.activeLoans()+" / "+current.maxLoans()+"\n逾期："+(current.overdue()?"是":"否")+"\n\n图书：《"+current.title()+"》\n条码："+current.barcode()+"\n馆藏状态："+current.copyStatus()+"\n\n校验结果："+current.message());execute.setEnabled(current.allowed());});}
    private void execute(){if(current==null||!current.allowed())return;if(operation.getSelectedItem()==LibraryCirculationOperation.BORROW){if(JOptionPane.showConfirmDialog(this,"确认替 "+current.displayName()+" 借出《"+current.title()+"》？","办理借阅",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)runRequest(()->client.adminBorrowLibraryCopy(sessionToken,current.username(),current.barcode()),r->{info("借阅办理成功");validateInput();});}else{LibraryReturnCondition value=(LibraryReturnCondition)condition.getSelectedItem();if(value==LibraryReturnCondition.LOST&&reason.getText().isBlank()){error("遗失关闭必须填写原因");return;}if(JOptionPane.showConfirmDialog(this,value==LibraryReturnCondition.LOST?"确认将该馆藏登记为遗失并关闭借阅？":"确认归还该馆藏？","办理归还",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)runRequest(()->client.adminReturnLibraryCopy(sessionToken,current.barcode(),value,reason.getText().trim()),r->{info("归还办理成功");validateInput();});}}
}
