package com.vcampus.client.ui;

import com.vcampus.client.network.VCampusClient;
import com.vcampus.common.model.LibraryCopyStatus;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.*;
import java.util.List;

final class LibraryInventoryPanel extends LibraryPanel {
    private final DefaultTableModel booksModel=model("ID","书名","作者","ISBN","分类","启用","可借/总藏"),copiesModel=model("ID","条码","书名","书架","状态","原因");private final JTable books=new JTable(booksModel),copies=new JTable(copiesModel);private java.util.List<LibraryViewData.CatalogRow>bookRows=List.of();private java.util.List<LibraryViewData.CopyRow>copyRows=List.of();private final JTextField bookKeyword=field(14),copyKeyword=field(14);
    LibraryInventoryPanel(VCampusClient c,String t){super(c,t);setLayout(new BorderLayout());JTabbedPane inner=new JTabbedPane();inner.addTab("书目",books());inner.addTab("实体馆藏",copies());add(inner);loadBooks();loadCopies();}
    private JPanel books(){JPanel p=new JPanel(new BorderLayout(0,12));p.setOpaque(false);JPanel bar=toolbar();bar.add(new JLabel("书名 / ISBN"));bar.add(bookKeyword);JButton search=primary("查询"),create=mutation("新建书目"),edit=mutation("编辑"),toggle=mutation("启用 / 停用");bar.add(search);bar.add(create);bar.add(edit);bar.add(toggle);styleTable(books);p.add(bar,BorderLayout.NORTH);p.add(scroll(books));search.addActionListener(e->loadBooks());create.addActionListener(e->bookDialog(null));edit.addActionListener(e->{int i=selected(books);if(i>=0)bookDialog(bookRows.get(i));});toggle.addActionListener(e->toggleBook());return p;}
    private JPanel copies(){JPanel p=new JPanel(new BorderLayout(0,12));p.setOpaque(false);JPanel bar=toolbar();bar.add(new JLabel("条码 / 书名"));bar.add(copyKeyword);JButton search=primary("查询"),create=mutation("新增馆藏"),status=mutation("变更状态");bar.add(search);bar.add(create);bar.add(status);styleTable(copies);p.add(bar,BorderLayout.NORTH);p.add(scroll(copies));search.addActionListener(e->loadCopies());create.addActionListener(e->copyDialog());status.addActionListener(e->statusDialog());return p;}
    private void loadBooks(){runRequest(()->client.searchLibraryCatalog(sessionToken,bookKeyword.getText().trim(),"",1),r->{bookRows=LibraryViewData.catalogPage(r).rows();booksModel.setRowCount(0);for(var x:bookRows)booksModel.addRow(new Object[]{x.bookId(),x.title(),x.authors(),x.isbn(),x.category(),x.enabled()?"是":"否",x.availableCopies()+" / "+x.totalCopies()});});}
    private void loadCopies(){Map<String,String>f=new LinkedHashMap<>();f.put("keyword",copyKeyword.getText().trim());f.put("page","1");runRequest(()->client.searchLibraryCopies(sessionToken,f),r->{copyRows=LibraryViewData.copyPage(r).rows();copiesModel.setRowCount(0);for(var x:copyRows)copiesModel.addRow(new Object[]{x.copyId(),x.barcode(),x.title(),x.shelfLocation(),x.status(),x.statusReason()});});}
    private void bookDialog(LibraryViewData.CatalogRow x){JTextField isbn=new JTextField(x==null?"":x.isbn()),title=new JTextField(x==null?"":x.title()),authors=new JTextField(x==null?"":x.authors()),publisher=new JTextField(x==null?"":x.publisher()),year=new JTextField(x==null||x.publishYear()==null?"":x.publishYear().toString()),category=new JTextField(x==null?"":x.category());JTextArea desc=new JTextArea(x==null?"":x.description(),4,28);Object[]form={"ISBN",isbn,"书名",title,"作者",authors,"出版社",publisher,"出版年",year,"分类",category,"简介",new JScrollPane(desc)};if(JOptionPane.showConfirmDialog(this,form,x==null?"新建书目":"编辑书目",JOptionPane.OK_CANCEL_OPTION)!=JOptionPane.OK_OPTION)return;Map<String,String>v=new LinkedHashMap<>();v.put("isbn",isbn.getText());v.put("title",title.getText());v.put("authors",authors.getText());v.put("publisher",publisher.getText());v.put("publishYear",year.getText());v.put("category",category.getText());v.put("description",desc.getText());if(x!=null)v.put("bookId",Long.toString(x.bookId()));runRequest(()->x==null?client.createLibraryBook(sessionToken,v):client.updateLibraryBook(sessionToken,v),r->{info(r.message());loadBooks();});}
    private void toggleBook(){int i=selected(books);if(i<0)return;var x=bookRows.get(i);runRequest(()->client.setLibraryBookEnabled(sessionToken,x.bookId(),!x.enabled()),r->{info(r.message());loadBooks();});}
    private void copyDialog(){JTextField bookId=new JTextField(),barcode=new JTextField(),shelf=new JTextField();if(JOptionPane.showConfirmDialog(this,new Object[]{"书目 ID",bookId,"馆藏条码",barcode,"书架位置",shelf},"新增馆藏",JOptionPane.OK_CANCEL_OPTION)!=JOptionPane.OK_OPTION)return;Map<String,String>v=Map.of("bookId",bookId.getText(),"barcode",barcode.getText(),"shelfLocation",shelf.getText());runRequest(()->client.createLibraryCopy(sessionToken,v),r->{info(r.message());loadCopies();});}
    private void statusDialog(){int i=selected(copies);if(i<0)return;var x=copyRows.get(i);if(x.status()==LibraryCopyStatus.ON_LOAN){error("借出中的馆藏不能手工变更状态");return;}JComboBox<LibraryCopyStatus>status=new JComboBox<>(new LibraryCopyStatus[]{LibraryCopyStatus.AVAILABLE,LibraryCopyStatus.LOST,LibraryCopyStatus.DAMAGED,LibraryCopyStatus.WITHDRAWN});JTextField reason=new JTextField();if(JOptionPane.showConfirmDialog(this,new Object[]{"新状态",status,"原因",reason},"变更馆藏状态",JOptionPane.OK_CANCEL_OPTION)!=JOptionPane.OK_OPTION)return;LibraryCopyStatus value=(LibraryCopyStatus)status.getSelectedItem();if(value!=LibraryCopyStatus.AVAILABLE&&reason.getText().isBlank()){error("该状态必须填写原因");return;}runRequest(()->client.setLibraryCopyStatus(sessionToken,x.copyId(),value.name(),reason.getText().trim()),r->{info(r.message());loadCopies();});}
    private DefaultTableModel model(String...columns){return new DefaultTableModel(columns,0){public boolean isCellEditable(int r,int c){return false;}};}
}
